name: .NET

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: cd ProducerCadastro & dotnet restore
    - name: Build
      run: cd ProducerCadastro & dotnet build --no-restore
    - name: Test
      run: cd ProducerCadastro & dotnet test --no-build --verbosity normal
